services:
  - type: web
    name: playpro2
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: NEXT_PUBLIC_RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /login
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /signup
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /